// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TinyLibrary.Infrastructure.Persistence;

#nullable disable

namespace TinyLibrary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260728080339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TinyLibrary.Domain.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Author");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AvailableCopies");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Isbn");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalCopies");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");
                });

            modelBuilder.Entity("TinyLibrary.Domain.Models.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT")
                        .HasColumnName("BookId");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("DueAt");

                    b.Property<DateTimeOffset>("LoanedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("LoanedAt");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT")
                        .HasColumnName("MemberId");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ReturnedAt");

                    b.HasKey("Id");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("TinyLibrary.Domain.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("JoinedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTimeOffset?>("PenalizedUntil")
                        .HasColumnType("TEXT")
                        .HasColumnName("PenalizedUntil");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
